name: CI to Docker hub

on:
  push:
    branches: [ main ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }} 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          logout: true   
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: xtendaccounting/gin-api:latest 
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
